# Generated by Django 6.0.7 on 2026-08-20 13:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourrierSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre_entrant', models.CharField(max_length=50, unique=True)),
                ('numero_courrier_sortant', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('nom_destination', models.CharField(max_length=200)),
                ('fonction_destination', models.CharField(max_length=200)),
                ('structure_destinataire', models.CharField(max_length=200)),
                ('ville_destinataire', models.CharField(max_length=100)),
                ('signataire', models.CharField(max_length=200)),
                ('structure_signataire', models.CharField(max_length=200)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('delai_de_reponse', models.DateTimeField(blank=True, null=True)),
                ('confidentialite', models.BooleanField(blank=True, default=False, null=True)),
                ('date_envoie', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('lien_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M.', max_length=10)),
                ('nom_prenom', models.CharField(max_length=150, verbose_name='Nom et Prénom')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('type_agent', models.CharField(max_length=100)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('adresse_local', models.CharField(blank=True, default='', max_length=150)),
                ('observations', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profil/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fonction', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
                'ordering': ['nom_prenom'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('SECRETAIRE', 'Secrétaire'), ('SERVICE', 'Service'), ('ADMIN', 'Administrateur'), ('DG', 'Directeur')], default='SERVICE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50)),
                ('civilite', models.CharField(blank=True, max_length=10, null=True)),
                ('raison_social', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_local', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('boite_postale', models.CharField(blank=True, max_length=50, null=True)),
                ('secteur_activite', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_structure', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourrierEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'ordre")),
                ('reference', models.CharField(max_length=200, unique=True, verbose_name='Référence interne')),
                ('reference_doc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence du document')),
                ('objet', models.CharField(max_length=255)),
                ('type_courrier', models.CharField(choices=[('lettre', 'Lettre'), ('demande', 'Demande'), ('facture', 'Facture'), ('invitation', 'Invitation'), ('reclamation', 'Réclamation'), ('note', 'Note'), ('convocation', 'Convocation'), ('rapport', 'Rapport'), ('autre', 'Autre')], default='lettre', max_length=20, verbose_name='Type de courrier')),
                ('nature_courrier', models.CharField(blank=True, choices=[('administratif', 'Administratif'), ('commercial', 'Commercial'), ('juridique', 'Juridique'), ('financier', 'Financier'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Nature du courrier')),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('importante', 'Importante'), ('urgente', 'Urgente'), ('tres_urgente', 'Très urgente')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('arrive', 'Arrivé'), ('a_assigner', 'À assigner'), ('transmis', 'Transmis'), ('en_cours', 'En cours de traitement'), ('en_attente', 'En attente de précision'), ('traite', 'Traité'), ('archive', 'Archivé')], default='arrive', max_length=20)),
                ('nom_expediteur', models.CharField(max_length=200)),
                ('fonction_expediteur', models.CharField(blank=True, max_length=200, null=True)),
                ('structure_expediteur', models.CharField(blank=True, max_length=200, null=True)),
                ('ville_expediteur', models.CharField(blank=True, max_length=100, null=True)),
                ('pays_expediteur', models.CharField(blank=True, max_length=100, null=True)),
                ('signataire', models.CharField(blank=True, max_length=200, null=True)),
                ('structure_signataire', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(verbose_name='Date du courrier')),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('debut_travaux', models.DateField(blank=True, null=True)),
                ('fin_travaux', models.DateField(blank=True, null=True)),
                ('droit_de_reponse', models.BooleanField(default=False, verbose_name='Nécessite un droit de réponse')),
                ('date_reponse', models.DateField(blank=True, null=True)),
                ('delai_de_reponse', models.DateField(blank=True, null=True)),
                ('confidentialite', models.BooleanField(default=False, verbose_name='Courrier confidentiel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('courrier_sortant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.courriersortant')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.personnel')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.societe')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_document', models.CharField(blank=True, max_length=255, null=True)),
                ('repertoire_document', models.FileField(upload_to='doc/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('consigne', models.CharField(blank=True, max_length=200, null=True)),
                ('courrier_entrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_finaux', to='courrier.courrierentrant')),
                ('courrier_sortant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_finaux', to='courrier.courriersortant')),
            ],
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.personnel'),
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pj', models.CharField(blank=True, max_length=100, null=True)),
                ('si_numerisation', models.BooleanField(blank=True, default=False, null=True)),
                ('repertoire_pj', models.FileField(blank=True, null=True, upload_to='piece/')),
                ('nom_original', models.CharField(max_length=255)),
                ('taille', models.BigIntegerField()),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
                ('courrier_entrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='courrier.courrierentrant')),
                ('courrier_sortant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='courrier.courriersortant')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_travaux', models.CharField(max_length=100)),
                ('date_debut_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_fin_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_debut_effective', models.DateTimeField(blank=True, null=True)),
                ('date_fin_effective', models.DateTimeField(blank=True, null=True)),
                ('si_distanciel_presenciel', models.BooleanField(blank=True, default=False, null=True)),
                ('lieu_seance', models.CharField(max_length=200)),
                ('observations', models.TextField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('courrier_entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.courrierentrant')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagemenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.pagemenu')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='courrier.personnel')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.profil')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.societe'),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_structure', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=100)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_dirigees', to='courrier.personnel')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.societe')),
                ('type_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.typestructure')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_personnel', to='courrier.structure'),
        ),
        migrations.CreateModel(
            name='Ampliateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('type_destinataire', models.CharField(blank=True, default='', max_length=200)),
                ('courrier_entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampliateurs', to='courrier.courrierentrant')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampliations', to='courrier.personnel')),
            ],
            options={
                'verbose_name': 'Ampliateur',
                'verbose_name_plural': 'Ampliateurs',
                'unique_together': {('courrier_entrant', 'personnel')},
            },
        ),
    ]
