# Generated by Django 6.0.7 on 2026-07-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
