# Generated by Django 6.0.7 on 2026-07-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courrier', '0002_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourrierSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre_entrant', models.CharField(max_length=50, unique=True)),
                ('numero_courrier_sortant', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('nom_destination', models.CharField(max_length=200)),
                ('fonction_destination', models.CharField(max_length=200)),
                ('structure_destinataire', models.CharField(max_length=200)),
                ('ville_destinataire', models.CharField(max_length=100)),
                ('signataire', models.CharField(max_length=200)),
                ('structure_signataire', models.CharField(max_length=200)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('delai_de_reponse', models.DateTimeField(blank=True, null=True)),
                ('confidentialite', models.BooleanField(blank=True, default=False, null=True)),
                ('date_envoie', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(max_length=10)),
                ('nom_prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('type_agent', models.CharField(max_length=100)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_local', models.CharField(max_length=150)),
                ('observations', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profil/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fonction', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50)),
                ('civilite', models.CharField(blank=True, max_length=10, null=True)),
                ('raison_social', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_local', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('boite_postale', models.CharField(blank=True, max_length=50, null=True)),
                ('secteur_activite', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_structure', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourrierEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('nom_expediteur', models.CharField(max_length=200)),
                ('fonction_expediteur', models.CharField(max_length=200)),
                ('structure_expediteur', models.CharField(max_length=200)),
                ('ville_expediteur', models.CharField(max_length=100)),
                ('signataire', models.CharField(max_length=200)),
                ('structure_signataire', models.CharField(max_length=200)),
                ('date_reponse', models.DateField(blank=True, null=True)),
                ('delai_de_reponse', models.DateField(blank=True, null=True)),
                ('confidentialite', models.BooleanField(default=False)),
                ('date_reception', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('debut_travaux', models.DateField(auto_now=True)),
                ('fin_travaux', models.DateField(auto_now=True)),
                ('courrier_sortant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.courriersortant')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.personnel')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.societe')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_document', models.CharField(blank=True, max_length=255, null=True)),
                ('repertoire_document', models.FileField(upload_to='doc/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('consigne', models.CharField(blank=True, max_length=200, null=True)),
                ('courrier_entrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.courrierentrant')),
                ('courrier_sortant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.courriersortant')),
            ],
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.personnel'),
        ),
        migrations.CreateModel(
            name='Ampliateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, null=True)),
                ('type_destinataire', models.CharField(blank=True, max_length=200, null=True)),
                ('courrier_entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.courrierentrant')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pj', models.CharField(blank=True, max_length=100, null=True)),
                ('si_numerisation', models.BooleanField(blank=True, default=False, null=True)),
                ('repertoire_pj', models.FileField(blank=True, null=True, upload_to='piece/')),
                ('courrier_entrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.courrierentrant')),
                ('courrier_sortant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.courriersortant')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_travaux', models.CharField(max_length=100)),
                ('date_debut_prevue', models.DateTimeField(auto_now=True)),
                ('date_fin_prevue', models.DateTimeField(auto_now=True)),
                ('date_debut_effective', models.DateTimeField(blank=True, null=True)),
                ('date_fin_effective', models.DateTimeField(blank=True, null=True)),
                ('si_distanciel_presenciel', models.BooleanField(blank=True, default=False, null=True)),
                ('lieu_seance', models.CharField(max_length=200)),
                ('observations', models.TextField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('courrier_entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.courrierentrant')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.societe'),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_structure', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=100)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_dirigees', to='courrier.personnel')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.societe')),
                ('type_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.typestructure')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_personnel', to='courrier.structure'),
        ),
    ]
