# Generated by Django 6.0.7 on 2026-07-22 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('lien_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=200)),
                ('mot_de_pass', models.CharField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.CharField(max_length=200)),
                ('inactivite', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagemenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.pagemenu')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.profil')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.utilisateur')),
            ],
        ),
    ]
