# Generated by Django 6.0.7 on 2026-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0004_pagemenu_profil_utilisateur_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
