# Generated by Django 6.0.7 on 2026-07-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0006_alter_utilisateur_options_alter_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.AddField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('SECRETAIRE', 'Secrétaire'), ('SERVICE', 'Service'), ('ADMIN', 'Administrateur'), ('DG', 'Directeur')], default='SERVICE', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.profil'),
        ),
    ]
