# Generated by Django 6.0.7 on 2026-07-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0007_remove_permission_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrierentrant',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='debut_travaux',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='fin_travaux',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.personnel'),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.societe'),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='statut',
            field=models.CharField(choices=[('arrive', 'Arrivé'), ('a_assigner', 'À assigner'), ('transmis', 'Transmis'), ('en_cours', 'En cours de traitement'), ('en_attente', 'En attente de précision'), ('traite', 'Traité'), ('archive', 'Archivé')], default='arrive', max_length=20),
        ),
    ]
