# Generated by Django 6.0.7 on 2026-07-30 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0008_alter_courrierentrant_date_modification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrierentrant',
            name='courrier_sortant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.courriersortant'),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.personnel'),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.societe'),
        ),
    ]
